config/routes.rb
Rulez::Engine.routes.draw do

  root to: 'static#index'

  resources :contexts
  resources :rules do
    resources :alternatives, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :variables

  get 'contexts/:id/variables', to: 'contexts#variables', as: 'context_variables'
  post 'rules/:id/sort_alternatives', to: 'rules#sort_alternatives'
  get 'doctor', to: 'static#doctor'
  get 'displaylog', to: 'static#displaylog'
  get 'clearlogfile', to: 'static#clearlogfile'
  get 'accessdenied', to: 'static#accessdenied'
end

app/models/rulez/alternative.rb
# == Schema Information
#
# Table name: rulez_alternatives
#
#  id          :integer          not null, primary key
#  description :string(255)
#  condition   :text
#  alternative :text
#  rule_id     :integer
#  priority    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

module Rulez

  # 
  # Describes an alternative to a rule.
  # When its condition is true, the alternative substitute the original rule.
  # 
  class Alternative < ActiveRecord::Base
    #rails 5 strong parameters
    # attr_accessible :description, :condition, :alternative

    belongs_to :rule
    has_one :context, through: :rule

    # validations
    validates :description, :rule, presence: true
    validates :condition, :alternative, presence: true, syntax: true
    validates :priority, presence:true, numericality: true

    # 
    # Returns an array containing all the parameters of the rule
    # 
    # @return [Array] The list of all the parameters of the rule
    def get_parameters_list
      rule.get_parameters_list
    end
  end
end

app/models/rulez/context.rb
# == Schema Information
#
# Table name: rulez_contexts
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

module Rulez

  # 
  # A context defines a set of variables and functions that can be referenced and evaluated by rules.
  # A rule must be associated with a context for using its variables and functions.
  # All variables that are not defined in that context are considered invalid.
  # 
  class Context < ActiveRecord::Base
    # attr_accessible :description, :name, :variable_ids

    #associations
    has_many :rules
    has_and_belongs_to_many :variables, join_table: :rulez_contexts_variables

    #validations
    validates :name, presence: true, uniqueness: true
    validates :description, presence:true
  end
end

app/models/rulez/symbol.rb
# == Schema Information
#
# Table name: rulez_symbols
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  model       :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

module Rulez

  # 
  # A symbol is a variable name that is guaranteed to be referenceable and evaluable.
  # Defining symbols allows to design rules that directly reference and evaluate application objects.
  # 
  class Symbol < ActiveRecord::Base
    attr_accessible :description, :name, :model

    #associations
    has_and_belongs_to_many :context, join_table: :rulez_contexts_symbols

    #validations
    validates :name, presence: true, uniqueness: true
    validates :description, presence: true
    validates :model, presence: true
    
  end
end

app/controllers/rulez/alternatives_controller.rb
require_dependency "rulez/application_controller"

module Rulez
  class AlternativesController < ApplicationController
    before_filter :set_rule

    # GET /alternatives/new
    def new
      @alternative = @rule.alternatives.new
    end

    # GET /alternatives/1/edit
    def edit
      set_alternative
    end

    # POST /alternatives
    def create
      i = 1
      @rule.alternatives.sort{|a,b| a.priority <=> b.priority}.each do |alternative|
        alternative.priority = i
        alternative.save
        i += 1
      end

      @alternative = @rule.alternatives.new(req_param)
      @alternative.priority = i

      if @alternative.save
        errors = Rulez::doctor
        err_msg = nil
        if !errors.empty?
          err_msg = 'Due to this create operation some inconsistencies have been created. Go to DashBoard and Run Doctor to fix them.'
        end
        redirect_to @rule, notice: 'Alternative was successfully created.', alert: err_msg
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /alternatives/1
    def update
      set_alternative
      if @alternative.update_attributes(req_param)
        errors = Rulez::doctor
        err_msg = nil
        if !errors.empty?
          err_msg = 'Due to this edit operation some inconsistencies have been created. Go to DashBoard and Run Doctor to fix them.'
        end
        redirect_to @rule, notice: 'Alternative was successfully updated.', alert: err_msg
      else
        render action: 'edit'
      end
    end

    # DELETE /alternatives/1
    def destroy
      set_alternative
      @alternative.destroy
      i = 1
      @rule.alternatives.sort{|a,b| a.priority <=> b.priority}.each do |alternative|
        if alternative.id != @alternative.id
          alternative.priority = i
          alternative.save
          i += 1
        end
      end
      errors = Rulez::doctor
        err_msg = nil
        if !errors.empty?
          err_msg = 'Due to this delete operation some inconsistencies have been created. Go to DashBoard and Run Doctor to fix them.'
        end
      redirect_to rule_path(@rule), notice: 'Alternative was successfully destroyed.', alert: err_msg
    end

    private

      # 
      # Set current rule
      # 
      # @return [type] [description]
      def set_rule
        @rule ||= Rule.find(params[:rule_id])
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_alternative
        @alternative = @rule.alternatives.find(params[:id])
      end

      def req_param
        params.require(:alternative).permit(:description, :condition, :alternative)
      end
  end
end

app/controllers/rulez/application_controller.rb
module Rulez

  class ApplicationController < ActionController::Base
    before_filter :authenticate

    private

    # 
    # This method restricts the access to the administration tools of Rulez.
    # The authentication is performed evaluating a rule called "admin_rulez",
    # that is set to "true" by default.
    # 
    def authenticate
      Rulez::set_rulez_target self
      if request.path != accessdenied_path && !Rulez::rulez?("admin_rulez")
        redirect_to accessdenied_path
      end
    end
  end
end

app/controllers/rulez/contexts_controller.rb
require_dependency "rulez/application_controller"

module Rulez

  # 
  # The Contexts Controller
  # 
  class ContextsController < ApplicationController

    # GET /contexts
    def index
      @contexts = Context.all
    end

    # GET /contexts/1
    def show
      set_context
    end

    # 
    # Renders the available variables for a given context.
    # This action is called in Ajax from other views
    # 
    def variables
      set_context
      @variables = @context.variables
      @functions = Rulez::get_methods_class.methods(false).map { |e| e.to_s }
      render layout: false
    end

    # GET /contexts/new
    def new
      @context = Context.new
    end

    # GET /contexts/1/edit
    def edit
      set_context
    end

    # POST /contexts
    def create
      @context = Context.new(req_param)

      if @context.save
        errors = Rulez::doctor
        err_msg = nil
        if !errors.empty?
          err_msg = 'Due to this create operation some inconsistencies have been created. Go to DashBoard and Run Doctor to fix them.'
        end
        redirect_to @context, notice: 'Context was successfully created.', alert: err_msg
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /contexts/1
    def update
      set_context
      if @context.update_attributes(req_param)
        errors = Rulez::doctor
        err_msg = nil
        if !errors.empty?
          err_msg = 'Due to this edit operation some inconsistencies have been created. Go to DashBoard and Run Doctor to fix them.'
        end
        redirect_to @context, notice: 'Context was successfully updated.', alert: err_msg
      else
        render action: 'edit'
      end
    end

    # DELETE /contexts/1
    def destroy
      set_context
      @context.destroy
      errors = Rulez::doctor
      err_msg = nil
      if !errors.empty?
        err_msg = 'Due to this delete operation some inconsistencies have been created. Go to DashBoard and Run Doctor to fix them.'
      end
      redirect_to contexts_url, notice: 'Context was successfully destroyed.', alert: err_msg
    end

    private
      # 
      # Set the @context variable, from the given id
      # 
      # @return [Context] the current context
      def set_context
        @context = Context.find(params[:id])
      end

      def req_param
        params.require(:context).permit(:description, :name, :variable_ids)
      end
  end
end

app/controllers/rulez/rules_controller.rb
require_dependency "rulez/application_controller"

module Rulez

  # 
  # The rules controller
  # 
  class RulesController < ApplicationController

    # GET /rules
    def index
      @rules = Rule.all
    end

    # GET /rules/1
    def show
      set_rule
    end

    # GET /rules/new
    def new
      @rule = Rule.new
      set_contexts
    end

    # GET /rules/1/edit
    def edit
      set_rule
      set_contexts
    end

    # POST /rules
    def create
      logger.debug "======#{req_param.to_json}======"
      set_contexts
      @rule = Rule.new(req_param)
      if @rule.save
        errors = Rulez::doctor
        err_msg = nil
        if !errors.empty?
          err_msg = 'Due to this create operation some inconsistencies have been created. Go to DashBoard and Run Doctor to fix them.'
        end
        Engine::info_log("Rule #{@rule.name} was successfully created!")
        redirect_to @rule, notice: "Rule #{@rule.name} was successfully created.", alert: err_msg
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /rules/1
    def update
      logger.debug "======#{req_param.to_json}======"
      set_rule
      set_contexts
      if @rule.update_attributes(req_param)
        errors = Rulez::doctor
        err_msg = nil
        if !errors.empty?
          err_msg = 'Due to this edit operation some inconsistencies have been created. Go to DashBoard and Run Doctor to fix them.'
        end
        Engine::info_log("Rule #{@rule.name} was successfully updated!")
        redirect_to @rule, notice: "Rule #{@rule.name} was successfully updated.", alert: err_msg
      else
        render action: 'edit'
      end
    end

    # DELETE /rules/1
    def destroy
      set_rule
      @rule.destroy
      respond_to do |format|
        format.html do
          errors = Rulez::doctor
          err_msg = nil
          if !errors.empty?
            err_msg = 'Due to this delete operation some inconsistencies have been created. Go to DashBoard and Run Doctor to fix them.'
          end
          redirect_to rules_url, notice: 'Rule was successfully destroyed.', alert: err_msg
        end
        format.json { render json: "{\"response\" : \"OK\"}" }
      end
    end

    # 
    # Sort the alternatives priority.
    # This action is called in ajax.
    # 
    # The request is made passing the parameter `:order` that is an array containing 
    # the alternative ids ordered by priority
    # 
    # example:
    # 
    # order: [3,12,5,4] # alt. 3 has priority 1 (highest), alt. 12 has priority 2 etc...
    # 
    def sort_alternatives
      set_rule
      new_order = params[:order].split(',').each { |e| e.slice! "alternative" }.map{ |e| e.to_i }
      old_order = @rule.alternatives.map { |e| e.id }

      #checks if all the alternatives referenced by params are the same found in current rule
      if (new_order - old_order).empty? && (old_order - new_order).empty?
        i = 1
        new_order.each do |aid|
          alternative = Alternative.find(aid)
          alternative.priority = i
          alternative.save
          i += 1
        end
        render json: "{\"response\" : \"OK\"}"
      else
        render json: "{\"response\" : \"ERROR: the alternatives provided does not belong to the given rule\"}"
      end
    end

    private

      # 
      # Set the current rule
      # 
      # @return [Rule] the current rule
      def set_rule
        @rule ||= Rule.find(params[:id])
      end


      # 
      # Return all the contexts
      # 
      # @return [Array] An array containing all the contexts
      def set_contexts
        @contexts ||= Context.all
      end

      def req_param
        params.require(:rule).permit(:description, :name, :rule, :context_id, :parameters)
      end
  end
end

app/controllers/rulez/static_controller.rb
require_dependency "rulez/application_controller"

module Rulez
  class StaticController < ApplicationController

    # 
    # The rulez engine homepage
    # 
    def index
    end

    # 
    # Executes rulez doctor and returns html page with errors or success message
    # 
    def doctor
      @errors = Rulez::doctor
      @errors.each do |e|
        case e[:type]
        when "Variable"
          e[:show_path] = variable_path(e[:ref])
          e[:edit_path] = edit_variable_path(e[:ref])
          e[:destroy_path] = variable_path(e[:ref])
        when "Rule"
          e[:show_path] = rule_path(e[:ref])
          e[:edit_path] = edit_rule_path(e[:ref])
          e[:destroy_path] = rule_path(e[:ref])
        when "Alternative"
          e[:show_path] = rule_path(e[:ref].rule)
          e[:edit_path] = edit_rule_alternative_path(e[:ref].rule, e[:ref])
          e[:destroy_path] = rule_alternative_path(e[:ref].rule, e[:ref])
        end
      end
      render layout: false
    end

    # 
    # Return the first n_rows of lines in the rulez log file depending on which kind of 
    # information the user has selected (FATAL, ERROR, WARNING, INFO, DEBUG) in json format.
    # 
    def displaylog
      respond_to do |format|
        format.json do
          Engine.flush_log
          filter = params[:checkbox_actives].map { |s| s.to_s }.join("|")
          nr = params[:n_rows]
          res = `grep -E -w \'#{filter}\' log/rulez.log | tail -n #{nr}`
          render json: res.split("\n").to_json
        end
      end
    end

    # 
    # clears the log file of rulez (log/rulez.log)
    # 
    def clearlogfile
      respond_to do |format|
        format.json do
          `>log/rulez.log`
          Engine.flush_log
          render json: "OK".to_json 
        end
      end
    end


    # 
    # Access Denied page
    # 
    def accessdenied
    end
  end
end

app/controllers/rulez/variables_controller.rb
require_dependency "rulez/application_controller"

module Rulez
  class VariablesController < ApplicationController
    
    # GET /variables
    def index
      @variables = Variable.all
    end

    # GET /variables/1
    def show
      set_variable
    end

    # GET /variables/new
    def new
      @variable = Variable.new
      set_models
    end

    # GET /variables/1/edit
    def edit
      set_variable
      set_models
    end

    # POST /variables
    def create
      @variable = Variable.new(req_param)
      set_models
      if @variable.save
        errors = Rulez::doctor
        err_msg = nil
        if !errors.empty?
          err_msg = 'Due to this create operation some inconsistencies have been created. Go to DashBoard and Run Doctor to fix them.'
        end
        redirect_to @variable, notice: 'Variable was successfully created.', alert: err_msg
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /variables/1
    def update
      set_variable
      set_models
      if @variable.update_attributes(req_param)
        errors = Rulez::doctor
        err_msg = nil
        if !errors.empty?
          err_msg = 'Due to this edit operation some inconsistencies have been created. Go to DashBoard and Run Doctor to fix them.'
        end
        redirect_to @variable, notice: 'Variable was successfully updated.', alert: err_msg
      else
        render action: 'edit'
      end
    end

    # DELETE /variables/1
    def destroy
      set_variable
      @variable.destroy
      respond_to do |format|
        format.html do
          errors = Rulez::doctor
          err_msg = nil
          if !errors.empty?
            err_msg = 'Due to this delete operation some inconsistencies have been created. Go to DashBoard and Run Doctor to fix them.'
          end
          redirect_to variables_url, notice: 'Variable was successfully destroyed.', alert: err_msg
        end
        format.json { render json: "{\"response\" : \"OK\"}" }
      end
    end

    private
      
      # 
      # Set the current variable
      # 
      # @return [Variable] the current variable
      def set_variable
        @variable = Variable.find(params[:id])
      end

      # 
      # Set the available models
      # 
      # @return [Array] the array of models available
      def set_models
        @models = Rulez::get_models
      end

      def req_param
        params.require(:variable).permit(:description, :name, :model)
      end
  end
end

app/helpers/rulez/alternatives_helper.rb
module Rulez
  module AlternativesHelper
  end
end

app/helpers/rulez/application_helper.rb
module Rulez
  module ApplicationHelper
  end
end

app/helpers/rulez/contexts_helper.rb
module Rulez
  module ContextsHelper
  end
end

app/helpers/rulez/rules_helper.rb
module Rulez
  module RulesHelper
  end
end

app/helpers/rulez/variables_helper.rb
module Rulez
  module VariablesHelper
  end
end

app/views/rulez/contexts/_form.html.erb
<div class='col-md-12'>
  <% if @context.errors.any? %>
    <div id='error_explanation' class='alert alert-danger'>
      <h4><%= pluralize(@context.errors.count, 'error') %> prohibited this context from being saved:</h4>
      <ul>
      <% @context.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>

<div class='col-md-6'>
  <%= form_for @context, html: { role: 'form' } do |f| %>
    <div class='form-group'>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :description %>
      <%= f.text_field :description, rows: 10, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :variables %>
      <%= f.select :variable_ids, Rulez::Variable.all.to_a.collect {|x| [x.name, x.id]}, {}, :multiple => true, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', contexts_path, class: 'btn btn-default' %>
    </div>
  <% end %>
</div>

app/views/rulez/contexts/_nav.html.erb
<% content_for :nav do %>
  <ul class='nav nav-pills'>
    <li><a href='<%= rulez.root_path %>'>Dashboard</a></li>
    <li class='active'><a href='<%= rulez.contexts_path %>'>Contexts</a></li>
    <li><a href='<%= rulez.rules_path %>'>Rules</a></li>
    <li><a href='<%= rulez.variables_path %>'>Variables</a></li>
  </ul>
<% end %>

app/views/rulez/contexts/edit.html.erb
<%= render partial: 'nav' %>

<div class="page-header">
  <h1>Editing context</h1>
</div>

<div class='row'>
  <%= render partial: 'form' %>
</div>

app/views/rulez/contexts/index.html.erb
<%= render partial: 'nav' %> 

<% if notice %>
  <div id='notice' class='alert alert-success'>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div id='alert' class='alert alert-danger'>
    <%= alert %>
  </div>
<% end %>

<div class='page-header'>
  <h1>Contexts</h1>
</div>

<div class='row'>
  <table class='table table-bordered table-hover'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Variables</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @contexts.each do |context| %>
        <tr>
          <td><%= context.name %></td>
          <td><%= context.description %></td>
          <td>
            <% context.variables.each do |sym| %>
              <%= sym.name %><br>
            <% end %>
          </td>
          <td>
            <div class='btn-group'>
              <%= link_to 'Show', context, class: 'btn btn-default btn-xs' %>
              <%= link_to 'Edit', edit_context_path(context), class: 'btn btn-default btn-xs' %>
              <%= link_to 'Destroy', context, class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= link_to 'New Context', new_context_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/rulez/contexts/new.html.erb
<%= render partial: 'nav' %>

<div class='page-header'>
  <h1>New Context</h1>
</div>

<div class='row'>
  <%= render partial: 'form' %>
</div>

app/views/rulez/contexts/show.html.erb
<%= render partial: 'nav' %>

<% if notice %>
  <div id='notice' class='alert alert-success'>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div id='alert' class='alert alert-danger'>
    <%= alert %>
  </div>
<% end %>

<div class='row'>
  <dl class='dl-horizontal'>
    <dt><strong>Name:</strong></dt>
      <dd><%= @context.name %></dd>
    <br>
    <dt><strong>Description:</strong></dt>
      <dd><%= @context.description %></dd>
    <br>
    <dt><strong>Variables:</strong></dt>
      <% @context.variables.each do |s| %>
        <dd><%= s.name %></dd>
      <% end %>
    <br>
  </dl>
  <div>
    <%= link_to 'Back', contexts_path, class: 'btn btn-default' %>
    <%= link_to 'Edit', edit_context_path(@context), class: 'btn btn-default' %>
    <%= link_to 'Destroy',
                @context,
                class: 'btn btn-danger',
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/rulez/contexts/symbols.html.erb
<strong>Available symbols (with descriptions):</strong><br>
<% @symbols.each do |sym| %>
  <p>
    <%= "#{sym.name} (#{sym.model})" %> 
    <span class="symbol_description">
      <%= " - " << sym.description if sym.description.present? %>
    </span>
    <% methods = (eval "#{sym.model}").new.public_methods(false) + (eval "#{sym.model}").new.attribute_names %>
    <% methods.each do |m| %>
      <br>
      &nbsp;&nbsp;
      <%= ".#{m}" %>
    <% end %>
  </p>
<% end %>

app/views/rulez/contexts/variables.html.erb
<strong>Available variables (with descriptions):</strong><br>
<% @variables.each do |sym| %>
  <p>
    <%= "#{sym.name} (#{sym.model})" %> 
    <span class="variable_description">
      <%= " - " << sym.description if sym.description.present? %>
    </span>
    <% methods = (eval "#{sym.model}").new.public_methods(false) + (eval "#{sym.model}").new.attribute_names %>
    <% methods.each do |m| %>
      <% if (!m.match(/\A_callback|\A_one_time_conditions_valid|\Avalidate_associated_records|\Abefore_|\Aafter_|\A_before_|\A_after_|\Aautosave_associated_records_for_/)) %>
        <br>
        &nbsp;&nbsp;
        <%= ".#{m}" %>
      <% end %>
    <% end %>
  </p>
<% end %>
<strong>Available functions:</strong><br>
<p>
  <% @functions.each do |f| %>
    <%= f %>
    <br>
  <% end %>
</p>